---
name: "export PHP_IDE_CONFIG='serverName=jobs.exads.rocks'"
command: "export PHP_IDE_CONFIG='serverName=jobs.exads.rocks'"
description: ~
arguments: []
tags: []
source_url: ~
author: ~
author_url: ~
shells: []
